- name: Edit /etc/shells
  ansible.builtin.lineinfile:
    dest: /etc/shells
    line: "/opt/homebrew/bin/zsh"
    state: present
  become: yes
  become_user: root

- name: Change user shell to brew zsh
  become: yes
  become_user: root
  user:
    name: "{{ ansible_user }}"
    shell: /opt/homebrew/bin/zsh

- name: Check marlonrichert/zsh-autocomplete repository
  stat:
    path: ~/ghq/github.com/marlonrichert/zsh-autocomplete
  register: zsh_autocomplete_repo

- name: Check out marlonrichert/zsh-autocomplete repository
  shell: |
    ghq get https://github.com/marlonrichert/zsh-autocomplete.git
  when: not zsh_autocomplete_repo.stat.exists
