- name: Edit /etc/shells
  ansible.builtin.lineinfile:
    dest: /etc/shells
    line: "/opt/homebrew/bin/zsh"
    state: present
  become: yes
  become_user: root

- name: Change user shell to brew zsh
  become: yes
  user:
    name: "{{ ansible_user }}"
    shell: /opt/homebrew/bin/zsh
