- name: Search ruby versions
  shell: |
    rbenv install --list | awk '
      match($0,/^2\.[7]\..+|^3\.[0-9]\..+/) {
        print $0
      }
    '| sort | uniq
  register: rbenv_rubies

- name: Install rubies
  shell: |
    rbenv install -s "{{ item }}"
  loop: "{{ rbenv_rubies.stdout_lines }}"
