- name: Touch .hushlogin
  ansible.builtin.file:
    path: ~/.hushlogin
    state: touch

- name: Check ~/src/nalabjp/dotfiles/.zshrc.local.{{ inventory_hostname }}.enc
  stat:
    path: ~/src/nalabjp/dotfiles/.zshrc.local.{{ inventory_hostname }}.enc
  register: zshrc_local_enc

- name: Create ~/.zshrc.local
  shell: |
    ansible-vault view ~/src/nalabjp/dotfiles/.zshrc.local.{{ inventory_hostname }}.enc --vault-password-file ~/.ansible-vault > ~/.zshrc.local
  when: zshrc_local_enc.stat.exists
