- name: Touch .hushlogin
  ansible.builtin.file:
    path: ~/.hushlogin
    state: touch

- name: Create ~/.zshrc.local
  shell: |
    ansible-vault view ~/ghq/github.com/nalabjp/dotfiles/.zshrc.local.{{ group_name }}.enc --vault-password-file ~/.ansible-vault > ~/.zshrc.local
